### ISSUE TITLE
Not compatible with Gradle 8.9 due to paramter change

### ISSUE THREAD

**Issue by HyCraftHD** [MinecraftForge/Artifactural#13]
With https://github.com/gradle/gradle/commit/90f772b5d4b5599653d435e9f10d364a5599608d the first parameter for the following method https://github.com/MinecraftForge/Artifactural/blob/564e94332e36f0933818ad8d6e5720c629f2a792/src/gradlecomp/java/net/minecraftforge/artifactural/gradle/GradleRepositoryAdapter.java#L258 has changed from ``ComponentArtifactMetadata`` to ``ComponentArtifactResolveMetadata`` resulting in the following issue
```java
> Receiver class net.minecraftforge.artifactural.gradle.GradleRepositoryAdapter$1$1 does not define or inherit an implementation of the resolved method 'abstract void resolveArtifactsWithType(org.gradle.internal.component.model.ComponentArtifactResolveMetadata, org.gradle.api.internal.component.ArtifactType, org.gradle.internal.resolve.result.BuildableArtifactSetResolveResult)' of interface org.gradle.api.internal.artifacts.ivyservice.ivyresolve.ModuleComponentRepositoryAccess.
```
when using with gradle 8.9+

**Comment by LexManos** [comment]
Thanks for the report/analysis. Simple enough to fix. Did a basic test with a Forge MDK on 8.9 and the full cycle worked.
